import Link from "next/link";
export const metadata = { title: "Privacy and data handling — Life Maxim" };
export default function PrivacyPage() {
  return <main id="main-content" className="privacy-page">
    <Link href="/">← Life Maxim</Link><h1>Your data and your control</h1>
    <p>This is the current development app’s data-handling summary, not a claim of production readiness. Avoid entering sensitive real-world information while testing.</p>
    <section><h2>What is stored</h2><p>Convex stores account records, profiles, entries, confirmed memories, tasks, research evidence, AI outputs, mail drafts and received messages. Access is checked against the signed-in account. Profiles separate context within an account; they are not separate accounts.</p></section>
    <section><h2>When information leaves the app</h2><ul>
      <li><strong>OpenAI voice:</strong> explicitly starting Interactive Mode voice shares microphone audio and the confirmed profile’s bounded context with GPT-Live-1. Life Maxim does not save raw audio or live captions, and requests provider session storage off. Provider processing policies still apply. Preparing a brief sends the selected local conversation notes to Luna through OpenRouter; only the brief you confirm is saved. Session and connection metadata are stored in Convex and included in your export.</li>
      <li><strong>OpenRouter:</strong> an AI request sends the entry input and the selected context needed for that request. Profile suggestions use profile metadata; guidance and planning can use confirmed memories. Planning may also include stored research excerpts. Luna handles suggestions; Terra handles contextual reasoning.</li>
      <li><strong>Firecrawl:</strong> a research request sends the search query and the country you select. Profile descriptions and memories are not included in that request.</li>
      <li><strong>AgentMail:</strong> creating an inbox provisions a provider inbox. Sending shares the approved recipient, subject and message. API polling retrieves received mail about every five minutes, with longer waits during errors or catch-up.</li>
    </ul><p>These providers have their own processing and retention practices. This app does not promise that forgetting or archiving a record deletes provider-side copies.</p></section>
    <section><h2>Decisions remain yours</h2><p>AI profile suggestions require confirmation. Plans create tasks only when you accept them. Email requires review, approval of a specific version, and a separate send action. Editing a profile invalidates earlier unsent mail approvals. Incoming messages and research text never authorize actions.</p></section>
    <section><h2>Controls available now</h2><p>You can edit entries and profiles, archive or restore a profile, and forget individual memories. Archiving retains history and pauses inbox checks; it does not delete the provider inbox or recall dispatched mail. Forgetting a memory removes it from the app’s memory list but does not erase older AI responses or provider records that may contain it.</p><p>New-entry drafts are kept in this workspace’s browser memory during navigation. They clear on refresh or sign-out. Saved entries and email drafts are stored in Convex.</p></section>
    <section><h2>Exporting your application records</h2><p>The Profiles screen offers a private JSON download of account-owned application records, including archived profiles and saved mail. Authentication records, login credentials, raw AI conversation history, external-provider copies and backups are excluded. Downloads are limited to 10,000 records or 16 MB; oversized or failed exports do not download a partial file. Pages are read separately, so avoid editing during export. This is not a point-in-time snapshot or restorable backup. Keep downloaded files secure.</p></section>
    <section><h2>Before public launch</h2><p>Self-service account deletion, configurable retention, a support contact and a finalized privacy policy are not available yet. They remain launch requirements. The app is not a substitute for qualified professional advice, and AI output can be inaccurate.</p></section>
    <Link href="/dashboard">Return to your workspace →</Link>
  </main>;
}
