/* eslint-disable @next/next/no-html-link-for-pages -- Deliberate full navigation: homepage access must not depend on the Vinext client router. */
import { ThemeToggle } from "@/components/theme-control";
import { BrandMark } from "@/components/brand-mark";
import { ArrowUpRight, ArrowRight, Compass, Layers3, Brain, ScanSearch, Scale, GitBranch, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Home() {
  return <main className="landing">
    <nav className="landing-nav"><a href="/" className="brand"><BrandMark/>Life Maxim<span className="beta">EARLY ACCESS</span></a><div className="nav-links"><ThemeToggle/><a href="#how-it-works">How it works</a><a href="#your-context">Your context</a><a href="/signin">Sign in <ArrowUpRight size={16}/></a><Button asChild><a href="/signup">Create account</a></Button></div></nav>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> YOUR AI LIFE MANAGER</div><h1>A clearer mind.<br/>A more <em>possible</em> life.</h1><p>Big decisions. Everyday responsibilities. The ideas you keep putting off. Bring them together, and find your next meaningful step.</p><div className="hero-actions"><Button size="lg" asChild><a href="/signup">Make room for what matters <ArrowRight size={18}/></a></Button><a href="#how-it-works">Meet Life Maxim <ArrowUpRight size={16}/></a></div><p className="quiet-note"><ShieldCheck size={16}/> Your context. Your decisions. Always your control.</p></div><div className="journey-card"><div className="journey-top"><Compass size={22}/><span>FROM A THOUGHT TO A WAY FORWARD</span><span className="mint-pill">One workspace</span></div><h2>What would you like<br/>to move forward?</h2><p>Start with what is on your mind.<br/>You do not need to have it all figured out.</p><div className="thought-box">“I have a goal, a few constraints,<br/>and a lot of unanswered questions.”<ArrowUpRight size={22}/></div><div className="journey-steps">{[{Icon:Brain,title:"Remember",desc:"Bring the right context"},{Icon:ScanSearch,title:"Research",desc:"Find supporting evidence"},{Icon:Scale,title:"Decide",desc:"Understand the trade-offs"},{Icon:GitBranch,title:"Act",desc:"Take the next step"}].map(({Icon,title,desc})=><div key={title}><Icon size={20}/><strong>{title}</strong><span>{desc}</span></div>)}</div><div className="journey-bottom"><ShieldCheck size={17}/> Anything consequential comes back to you.</div></div></section>
    <section id="how-it-works" className="how-section"><div className="section-intro"><span className="eyebrow">THINK CLEARLY. MOVE INTENTIONALLY.</span><h2>Less scattered.<br/>More connected.</h2><p>One objective connects what you know, what you discover, and what you choose to do.</p></div><div className="feature-grid">{[["01","Give your goal a home","Choose the part of your life it belongs to. Keep work, family, and personal ambitions in their own contexts."],["02","See the whole picture","Bring relevant memories together with fresh web evidence. Compare options and explore your assumptions."],["03","Turn clarity into progress","Build a practical plan, prepare the next action, and approve communications before they are sent."]].map(([n,t,d])=><article key={n}><span className="step-number">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section id="your-context" className="context-section"><Layers3 size={34}/><div><span className="eyebrow">MANY ROLES. ONE YOU.</span><h2>Space for every part of your life.</h2><p>Create your own profiles, or ask AI to suggest one. You confirm the context, and Life Maxim keeps each entry organized.</p></div><Button asChild variant="outline"><a href="/dashboard?intent=profile">Create your first profile <ArrowUpRight size={17}/></a></Button></section>
    <footer className="landing-footer"><a href="/" className="brand"><BrandMark/>Life Maxim</a><span>Your life, with room to move forward.</span><a href="/signin">Sign in <ArrowUpRight size={16}/></a></footer>
  </main>;
}
