"use client";
import { useState } from "react";
import { useMutation,useQuery } from "convex/react";
import { ConvexError } from "convex/values";
import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ACK_TEXT } from "@/convex/clientMailRules";
export function ClientMailHandler({profileId,onOpen}:{profileId:Id<"profiles">;onOpen:(id:Id<"objectives">)=>void}){
 const account=useQuery(api.billing.current,{});const paid=account?.provider==="paystack"&&account.tier!=="free";
 const data=useQuery(api.clientMail.list,{profileId});const register=useMutation(api.clientMail.register);const deactivate=useMutation(api.clientMail.deactivate);const configure=useMutation(api.clientMail.configure);const createInbox=useMutation(api.mail.createInbox);const mark=useMutation(api.clientMail.mark);const prepare=useMutation(api.clientMail.prepareReply);
 const [name,setName]=useState("");const [email,setEmail]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [filter,setFilter]=useState("all");
 async function perform(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setError("");try{await fn();}catch(e){setError(e instanceof ConvexError&&typeof e.data==="string"?e.data:"Could not complete this action. Please retry later.");}finally{setBusy(false);}}
 if(!data)return <p role="status">Loading client mail…</p>;
 return <section className="client-mail-handler"><h2>AgentMail Handler</h2><p>Register each client, then share your inbox address and their automatically assigned Client ID. Ask them to include the ID in the subject. IDs route mail; they are not passwords.</p>{error&&<p className="form-error" role="alert">{error}</p>}
 <Card className="detail-card"><h3>Your Customer-Service Inbox</h3><p>Premium and Premium Plus include one dedicated inbox per account, subject to platform capacity. Assign it to the profile you use for client work; other users cannot access it. Existing inboxes are retained.</p>{data.inbox?.address?<p>Inbox: <strong>{data.inbox.address}</strong></p>:<Button disabled={busy||!!data.inbox||!paid} onClick={()=>void perform(()=>createInbox({profileId}))}>{data.inbox?`Inbox ${data.inbox.status}`:paid?"Create My Customer-Service Inbox":"Premium Subscription Required"}</Button>}{data.inbox?.error&&<p role="alert" className="form-error">{data.inbox.error}</p>}
 <p>Checks run while you are offline, normally at least five minutes apart. Quotas and provider backoff can delay a check. Last check: {data.inbox?.lastPolledAt?new Date(data.inbox.lastPolledAt).toLocaleString():"Not yet recorded"}.</p>
 <p>Automatic acknowledgement: “{ACK_TEXT}” Only new matched, authenticated, non-automatic mail is eligible. Maximum one acknowledgement per client per day. Final replies always require your approval.</p>
 <div className="mail-handler-controls"><Button disabled={busy||data.inbox?.status!=="ready"} onClick={()=>void perform(()=>configure({profileId,enabled:true,acknowledge:false}))}>Enable AI Triage Only</Button><Button variant="outline" disabled={busy||data.inbox?.status!=="ready"} onClick={()=>void perform(()=>configure({profileId,enabled:true,acknowledge:true}))}>Enable Triage &amp; Automatic Acknowledgements</Button><Button variant="ghost" disabled={busy||!data.inbox?.handlerEnabled} onClick={()=>void perform(()=>configure({profileId,enabled:false,acknowledge:false}))}>Disable Handler</Button></div>
 <p>Handler: {data.inbox?.handlerEnabled?"Enabled":"Disabled"} · Auto-acknowledgement: {data.inbox?.acknowledge?"Enabled":"Disabled"}</p></Card>
 <Card className="detail-card"><h3>Register Customer / Client</h3><form className="stack-form" onSubmit={e=>{e.preventDefault();void perform(async()=>{await register({profileId,name,email});setName("");setEmail("");});}}><Label htmlFor="client-name">Client Name</Label><Input id="client-name" value={name} onChange={e=>setName(e.target.value)} required maxLength={120} disabled={busy}/><Label htmlFor="client-email">Registered Email Address</Label><Input id="client-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={254} disabled={busy}/><Button disabled={busy}>Register &amp; Assign Client ID</Button></form>
 <p>Only mail from the registered address can match this client. Deactivating a client stops future automatic processing.</p>{data.clients.map(c=><div className="registered-client" key={c._id}><strong>{c.name}</strong><span>{c.email}</span><code>{c.clientCode}</code><Button variant="outline" disabled={!c.active||busy} onClick={()=>void perform(()=>deactivate({id:c._id}))}>{c.active?"Deactivate":"Inactive"}</Button></div>)}</Card>
 <div className="section-heading"><h3>Client Mail Queue</h3><Label htmlFor="mail-status">Show</Label><select id="mail-status" value={filter} onChange={e=>setFilter(e.target.value)}>{["all","pending","in_progress","resolved","quarantined"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></div><p>Showing the latest 50 received messages. Unmatched mail is never automatically acknowledged.</p>
 {data.messages.filter(m=>filter==="all"||m.handlerStatus===filter).map(m=><Card key={m._id} className="detail-card"><h3>{m.subject}</h3><p>{m.sender} · {m.handlerStatus??"Not processed"} · AI: {m.triageStatus??"Not requested"} · Acknowledgement: {m.ackStatus??"None"}</p>{m.handlerReason&&<p>{m.handlerReason}</p>}{m.summary&&<p>{m.summary}</p>}{m.urgency&&<p>AI-assessed urgency: {m.urgency} — review before acting.</p>}<details><summary>Read Original Email</summary><p className="preserve-lines">{m.body}</p></details>{m.clientId&&m.handlerStatus!=="quarantined"&&<div className="mail-handler-controls"><Button disabled={busy} onClick={()=>void perform(async()=>onOpen(await prepare({id:m._id})))}>Review / Write Reply</Button><Button variant="outline" disabled={busy} onClick={()=>void perform(()=>mark({id:m._id,status:m.handlerStatus==="resolved"?"pending":"resolved"}))}>{m.handlerStatus==="resolved"?"Reopen":"Mark Resolved"}</Button></div>}</Card>)}
 </section>;
}
